### ISSUE TITLE
EndCrystal cannot be placed if the flag-limit-placing option is activated.

### ISSUE THREAD

**Issue by cutaxo** [Imhhitt/hhittRemover#3]
### ISSUE:

**I cannot put End Crystals and they are not cleaned either, I have the flag activated and the flag-limit-placing option activated as well.**

### CFG:

```
cleaner:
  ffacrystal:
    blocks:
      obsidian: 10
    entities:
      ender_crystal: 5
```
